In [31]:
import requests
import pandas as pd

# Replace 'YOUR_API_KEY' with your actual OpenFEC API key
API_KEY = 'BVTfalQokoMzRLDe1oCsI1k9T4OxyttZ56GQFOhZ'
ELECTION_YEAR = 2024  # Replace with your desired election year
PARTY = 'REP'  # R for Republican
OFFICE = 'H'
# &office={OFFICE} &election_year={ELECTION_YEAR}
# Base URL for the OpenFEC API request with parameters for active candidates
base_url = f'https://api.open.fec.gov/v1/candidates/?api_key={API_KEY}&party={PARTY}&candidate_status=C&election_year={ELECTION_YEAR}'

# Initialize an empty list to store all candidates
all_candidates = []
page = 1

while True:
    # Make a request to the OpenFEC API with the current page number
    response = requests.get(f'{base_url}&page={page}')
    
    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()
        
        # Extract candidate information
        candidates = data.get('results', [])
        
        # If no candidates are returned, exit the loop
        if not candidates:
            break
            
        # Add candidates to the list
        all_candidates.extend(candidates)
        
        # Check pagination details
        pagination = data.get('pagination', {})
        total_pages = pagination.get('pages', 0)
        
        # If we're on the last page, exit the loop
        if page >= total_pages:
            break
            
        # Move to the next page
        page += 1
    else:
        print(f"Failed to retrieve data: {response.status_code}")
        break

# Create a Pandas DataFrame from the collected candidates data
df = pd.DataFrame(all_candidates)

# Display the DataFrame
print(df)

     active_through candidate_id  candidate_inactive candidate_status  \
0              2024    H4TX31057               False                C
1              2024    H4MO07164               False                C
2              2024    H4CA49131               False                C
3              2024    H2FL21132               False                C
4              2024    H6AL04098               False                C
..              ...          ...                 ...              ...
992            2024    H4MT01041               False                C
993            2024    H2AZ07187               False                C
994            2024    H4TX19318               False                C
995            2024    H4MT02106               False                C
996            2024    H0NY06086               False                C

                                                cycles district  \
0                                               [2024]       31
1                                               [2024]       07
2                                               [2024]       49
3                                         [2022, 2024]       22
4    [1996, 1998, 2000, 2002, 2004, 2006, 2008, 201...       04
..                                                 ...      ...
992               [2014, 2016, 2018, 2020, 2022, 2024]       01
993                                 [2020, 2022, 2024]       03
994                                             [2024]       19
995                                             [2024]       02
996                                 [2020, 2022, 2024]       06

     district_number                                 election_districts  \
0               31.0                                               [31]
1                7.0                                               [07]
2               49.0                                               [49]
3               22.0                                           [22, 22]
4                4.0  [04, 04, 04, 04, 04, 04, 04, 04, 04, 04, 04, 0...
..               ...                                                ...
992              1.0                               [00, 00, 00, 01, 01]
993              3.0                                           [03, 03]
994             19.0                                               [19]
995              2.0                                               [02]
996              6.0                                       [06, 06, 06]

                                        election_years  federal_funds_flag  \
0                                               [2024]               False
1                                               [2024]               False
2                                               [2024]               False
3                                         [2022, 2024]               False
4    [1996, 1998, 2000, 2002, 2004, 2006, 2008, 201...               False
..                                                 ...                 ...
992                     [2014, 2016, 2018, 2022, 2024]               False
993                                       [2022, 2024]               False
994                                             [2024]               False
995                                             [2024]               False
996                                 [2020, 2022, 2024]               False

     ... incumbent_challenge_full  last_f2_date last_file_date  \
0    ...               Challenger    2023-04-19     2023-04-19
1    ...               Challenger    2024-02-03     2024-02-03
2    ...               Challenger    2023-05-01     2023-05-01
3    ...               Challenger    2024-01-08     2024-01-08
4    ...                Incumbent    2022-12-01     2022-12-01
..   ...                      ...           ...            ...
992  ...                Incumbent    2024-03-21     2024-03-21
993  ...                Open seat    2023-04-01     2023-04-01
994  ...               Challenger    2023-12-04     2023-12-04
995  ...                Open seat    2023-11-13     2023-11-13
996  ...               Challenger    2020-01-22     2024-07-25

               load_date                      name office office_full party  \
0    2024-01-30T21:02:09             ABEL, WILLIAM      H       House   REP
1    2024-04-10T21:00:50       ADAIR, JOHN DOUGLAS      H       House   REP
2    2023-07-17T21:04:17             ADAMS, SHERYL      H       House   REP
3    2024-01-08T20:59:26           ADEIMY, DEBORAH      H       House   REP
4    2023-08-06T21:01:25  ADERHOLT, ROBERT B. REP.      H       House   REP
..                   ...                       ...    ...         ...   ...
992  2024-03-21T21:00:16             ZINKE, RYAN K      H       House   REP
993  2023-07-22T21:02:58   ZINK, JEFFREY NELSON MR      H       House   REP
994  2024-02-20T20:59:54                ZINK, RYAN      H       House   REP
995  2024-04-17T21:00:58               ZINN, STACY      H       House   REP
996  2024-07-25T21:04:05             ZMICH, THOMAS      H       House   REP

           party_full state
0    REPUBLICAN PARTY    TX
1    REPUBLICAN PARTY    MO
2    REPUBLICAN PARTY    CA
3    REPUBLICAN PARTY    FL
4    REPUBLICAN PARTY    AL
..                ...   ...
992  REPUBLICAN PARTY    MT
993  REPUBLICAN PARTY    AZ
994  REPUBLICAN PARTY    TX
995  REPUBLICAN PARTY    MT
996  REPUBLICAN PARTY    NY

[997 rows x 24 columns]

In [32]:
wanted_columns = ['name', 'party', 'candidate_id', 'office', 'state', 'district']
df_active_republican_candidates = df[wanted_columns]
df_active_republican_candidates['name'] = df_active_republican_candidates['name'].str.replace('.', '', regex=False)

df_active_republican_candidates

/var/folders/kv/t7dj32kd6hs50xl35fksv5_h0000gn/T/ipykernel_89166/48728756.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_active_republican_candidates['name'] = df_active_republican_candidates['name'].str.replace('.', '', regex=False)

                        name party candidate_id office state district
0              ABEL, WILLIAM   REP    H4TX31057      H    TX       31
1        ADAIR, JOHN DOUGLAS   REP    H4MO07164      H    MO       07
2              ADAMS, SHERYL   REP    H4CA49131      H    CA       49
3            ADEIMY, DEBORAH   REP    H2FL21132      H    FL       22
4     ADERHOLT, ROBERT B REP   REP    H6AL04098      H    AL       04
..                       ...   ...          ...    ...   ...      ...
992            ZINKE, RYAN K   REP    H4MT01041      H    MT       01
993  ZINK, JEFFREY NELSON MR   REP    H2AZ07187      H    AZ       03
994               ZINK, RYAN   REP    H4TX19318      H    TX       19
995              ZINN, STACY   REP    H4MT02106      H    MT       02
996            ZMICH, THOMAS   REP    H0NY06086      H    NY       06

[997 rows x 6 columns]

In [33]:
import random
# List of selected issues
issues = [
    "Healthcare",
    "Economy",
    "Education",
    "Environment",
    "Public Safety",
    "Immigration",
    "Social Justice",
    "Infrastructure",
    "Voting Rights",
    "Taxes"
]

# Function to generate a random mapping for issues
def generate_issue_map():
    return {issue: random.randint(1, 10) for issue in issues}

# Apply the function to create a new column with the issue mappings
df_active_republican_candidates['issue_map'] = df_active_republican_candidates.apply(lambda row: generate_issue_map(), axis=1)

# Display the updated DataFrame
df_active_republican_candidates

/var/folders/kv/t7dj32kd6hs50xl35fksv5_h0000gn/T/ipykernel_89166/269480314.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_active_republican_candidates['issue_map'] = df_active_republican_candidates.apply(lambda row: generate_issue_map(), axis=1)

,name,party,candidate_id,office,state,district,issue_map
0,"ABEL, WILLIAM",REP,H4TX31057,H,TX,31,"{'Healthcare': 6, 'Economy': 1, 'Education': 8..."
1,"ADAIR, JOHN DOUGLAS",REP,H4MO07164,H,MO,07,"{'Healthcare': 8, 'Economy': 3, 'Education': 1..."
2,"ADAMS, SHERYL",REP,H4CA49131,H,CA,49,"{'Healthcare': 1, 'Economy': 1, 'Education': 4..."
3,"ADEIMY, DEBORAH",REP,H2FL21132,H,FL,22,"{'Healthcare': 3, 'Economy': 10, 'Education': ..."
4,"ADERHOLT, ROBERT B REP",REP,H6AL04098,H,AL,04,"{'Healthcare': 4, 'Economy': 7, 'Education': 3..."
...,...,...,...,...,...,...,...
992,"ZINKE, RYAN K",REP,H4MT01041,H,MT,01,"{'Healthcare': 5, 'Economy': 10, 'Education': ..."
993,"ZINK, JEFFREY NELSON MR",REP,H2AZ07187,H,AZ,03,"{'Healthcare': 2, 'Economy': 8, 'Education': 1..."
994,"ZINK, RYAN",REP,H4TX19318,H,TX,19,"{'Healthcare': 2, 'Economy': 9, 'Education': 9..."
995,"ZINN, STACY",REP,H4MT02106,H,MT,02,"{'Healthcare': 3, 'Economy': 8, 'Education': 3..."
996,"ZMICH, THOMAS",REP,H0NY06086,H,NY,06,"{'Healthcare': 1, 'Economy': 4, 'Education': 2..."

In [34]:
from pymongo import MongoClient

#curl -X DELETE http://localhost:8080/api/candidates/deleteAll


# Connect to MongoDB Atlas
import certifi
client = MongoClient("mongodb+srv://seekContact:seekContact@cluster27242.rl8uzla.mongodb.net/", tlsCAFile=certifi.where())

# Replace <dbname> with your database name
db = client['seekContact']  # Your MongoDB Atlas database name

# Replace 'candidates' with your collection name
collection = db['candidates']  # Your MongoDB Atlas collection name

# Prepare records to insert
records = []

for index, row in df_active_republican_candidates.iterrows():
    # Create a mapping dictionary
    candidate_data = {
        'name': row['name'],  # Map full_name to name
        'party': row['party'],  # Map political_party to party
        'issueScores': row['issue_map']  # Generate issue scores
    }
    records.append(candidate_data)

# Insert the records into MongoDB
collection.insert_many(records)

# Close the MongoDB connection
client.close()